/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary": "#be6500ff",
        "surface-tint": "#4d44e3",
        "on-surface-variant": "#464555",
        "on-background": "#191c1d",
        "status-proposal": "#06B6D4",
        "secondary-container": "#2170e4",
        "outline-variant": "#c7c4d8",
        "status-lost": "#EF4444",
        "status-won": "#10B981",
        "tertiary-container": "#6f3dd9",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#e1e3e4",
        "tertiary": "#571ac0",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-primary-container": "#dad7ff",
        "on-secondary-fixed-variant": "#004395",
        "error-container": "#ffdad6",
        "status-contacted": "#F59E0B",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "status-qualified": "#8B5CF6",
        "inverse-surface": "#2e3132",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#e3d5ff",
        "surface-glass": "rgba(255, 255, 255, 0.7)",
        "on-secondary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "status-new": "#3B82F6",
        "primary-container": "#4f46e5",
        "secondary-fixed-dim": "#adc6ff",
        "border-subtle": "#E5E7EB",
        "surface-dim": "#d9dadb",
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#d0bcff",
        "surface": "#f8f9fa",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#23005c",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#e9ddff",
        "primary": "#DE7356",
        "on-secondary-fixed": "#001a42",
        "outline": "#777587",
        "on-tertiary-fixed-variant": "#5516be",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#f8f9fa"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1440px",
        "element-gap": "12px",
        "section-gap": "48px",
        "gutter": "24px",
        "edge-margin": "32px",
        "stack-compact": "8px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
